export const USER_SET_EMAIL = "USER_SET_EMAIL",
    USER_SET_PASSWORD = "USER_SET_PASSWORD",
    USER_SET_FULLNAME = "USER_SET_FULLNAME",
    USER_SET_NAME = "USER_SET_NAME",
    USER_REGISTER_RESET_FORM = "USER_SET_FULLNAME",
    USER_BERANDA = "USER_BERANDA",
    SET_LOADING = "SET_LOADING"